version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: ./Waqq.Ly/Dockerfile  # Specify the path to the Dockerfile for the frontend
    ports:
      - "8080:8080"  # Map Host Port 443 to Frontend Container Port 8080
    networks:
      - custom_network  # Attach frontend to the custom network

  api:
    build: 
      context: .
      dockerfile: ./WaqqAPI/Dockerfile  # Specify the path to the Dockerfile for the API
    #Expose if development build

    ports:
      - "8070:8070"  # Map Host Port 8070 to API Container Port 8080
    networks:
      - custom_network  # Attach API to the custom network
  mongo:
    image: mongo:latest  # Use the latest MongoDB image
    #ports:
      #- "27017:27017"  # Map Host Port 27017 to MongoDB Container Port 27017
    networks:
      - custom_network  # Attach MongoDB to the custom network

networks:
  custom_network:
    driver: bridge
